[package]
name = "arbitary-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin-units = { git = "https://github.com/yancyribbens/rust-bitcoin.git", rev = "afc5f898ed0ce113888ef74f00b6877e223da156" }
proptest = "=1.2"
